### ISSUE TITLE
Issue with Astria AI callback

### ISSUE THREAD

**Issue by fred3105** [astriaai/headshots-starter#107]
Hey there, 

I am able to send images and create models through astria/train-model/route.ts
However I never get any callback from Astria.

VERCEL URL is set as mydomainname.com
promptWebhookWithParams looks like this https://mydomainname.com/astria/prompt-webhook?user_id=someuserid&webhook_secret=somesecret
trainWebhookWithParams looks like this https://mydomainname.com/astria/train-webhook?user_id=someuserid&webhook_secret=somesecret

I've tried simpler URLs but still nothing
The headers of my request are correct since the action creates a model on Astria
The body of my request looks like this

const body = {
      tune: {
        title: name,
        base_tune_id: 690204,
        name: type,
        branch: astriaTestModeIsOn ? "fast" : "sd15",
        token: "ohwx",
        image_urls: images,
        callback: trainWebhookWithParams,
        prompts_attributes: [
          {
            text: `some prompt`,
            callback: promptWebhookWithParams,
          },
          {
            text: `some prompt`,
            callback: promptWebhookWithParams,
          },
        ],
      },
    };

I've asked for help on Astria's discord but seem to be stuck, any idea of what could be going wrong?

**Comment by oceands** [comment]
Hey Fred, the problem isn't with Astria it is with Vercel go to your project and turn off Vercel authentication. This will allow the callback to work properly. Have a try and train another model with the change above, it should work normally as expected.

**Comment by fred3105** [comment]
> Hey Fred, the problem isn't with Astria it is with Vercel go to your project and turn off Vercel authentication. This will allow the callback to work properly. Have a try and train another model with the change above, it should work normally as expected.

That's not doing it for me, sucks, couple questions:
- What do you have in API settings on Astria.ai ? Here: https://www.astria.ai/users/edit#api
- What does your callback look like ? 
- Are you using the test environment on Astria or training a real model ?
- What does the body of your request look like ?

**Comment by oceands** [comment]
> > Hey Fred, the problem isn't with Astria it is with Vercel go to your project and turn off Vercel authentication. This will allow the callback to work properly. Have a try and train another model with the change above, it should work normally as expected.
> 
> That's not doing it for me, sucks, couple questions:
> - What do you have in API settings on Astria.ai ? Here: https://www.astria.ai/users/edit#api
> - What does your callback look like ? 
> - Are you using the test environment on Astria or training a real model ?
> - What does the body of your request look like ?

Hey Fred, I am using the real model, and my project is in the deployment stage. Try redeployment after said changes are made. It should work. If not, we can get on Zoom tomorrow, and I can show you how my project is set up.

**Comment by fred3105** [comment]
> > > Hey Fred, the problem isn't with Astria it is with Vercel go to your project and turn off Vercel authentication. This will allow the callback to work properly. Have a try and train another model with the change above, it should work normally as expected.
> > 
> > 
> > That's not doing it for me, sucks, couple questions:
> > 
> > * What do you have in API settings on Astria.ai ? Here: https://www.astria.ai/users/edit#api
> > * What does your callback look like ?
> > * Are you using the test environment on Astria or training a real model ?
> > * What does the body of your request look like ?
> 
> Hey Fred, I am using the real model, and my project is in the deployment stage. Try redeployment after said changes are made. It should work. If not, we can get on Zoom tomorrow, and I can show you how my project is set up.

Would love that, sent you an email

**Comment by apensotti** [comment]
Would be nice to share with the class. Anyway you can tell us how you solved this issue. I'm having a similar issue.

**Comment by fred3105** [comment]
@apensotti Despite having free credits I needed to add my credit card information, after that, everything ran smoothly
