### ISSUE TITLE
/auth/confirm does not exist 

### ISSUE THREAD

**Issue by mrisaacjoy** [astriaai/headshots-starter#111]
hi, for the magic link it redirects to auth/confirm?token_hash=pkce_8f32441e43a8c465c022a629d7891269c6bf0bbe74a48f1156e130e4&type=email

but it looks like you removed the /auth/confirm route in commit 9232d739e016a668bb7d28d4f1b76760e09d38d1, visible here: https://github.com/astriaai/headshots-starter/tree/9232d739e016a668bb7d28d4f1b76760e09d38d1

is there sth I am missing or like how is it supposed to work from supabase?

**Comment by Fdelro** [comment]
Hi, for me this gets me a 404, do you know how to solve the issue?

**Comment by mrisaacjoy** [comment]
@Fdelro yes, here you go: https://github.com/astriaai/headshots-starter/issues/112

I expect you did step 5, which is not needed (and auth/confrim does not exist so won't work). Change your magic link template in Supabase to the same one as signup and it'll work fine

**Comment by Fdelro** [comment]
Thanks a lot!
