### ISSUE TITLE
purchased credits don't appear on users account

### ISSUE THREAD

**Issue by brecht-horn** [astriaai/headshots-starter#115]
<img width="524" alt="Screenshot 2024-07-16 at 8 10 01 AM" src="https://github.com/user-attachments/assets/ff6f2c39-fcd3-4c65-8748-781736d335e8">

<img width="440" alt="Screenshot 2024-07-16 at 8 11 39 AM" src="https://github.com/user-attachments/assets/dd9369e4-e7b2-4752-9509-2dfe21844b0a">

<img width="142" alt="Screenshot 2024-07-16 at 8 11 47 AM" src="https://github.com/user-attachments/assets/9a7b33b6-23ff-480d-85dd-75013d1b9676">

My problem is that after purchasing credits successfully, the user's account does not get the credits, and the train model will still not proceed.

After purchasing credits I get a confirmation screen but no option to return to the site or anything, and have to hit the back button (Should I have it redirect back to the website, and if so, to what url?)

After hitting the back button and refreshing the user still shows 0 credits. My supabase seems to be correct in that it creates the user, but it is not creating "credits" property on the users account or adding the credit.

My stripe web hook secret, endpoint url and checkout.session.completed event seem to be correct from what I can tell:

<img width="574" alt="image" src="https://github.com/user-attachments/assets/e67abb0f-e388-4181-8887-510a49714477">

When stripe is disabled the train model works correctly.

New to all of this, but I believe I've set all the stripe env variables etc correctly and it is not working even after purchasing credits. Any suggestions would be much appreciated.

Thanks in advance.

**Comment by brecht-horn** [comment]
I see this on the stripe page:

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/03fe5872-5abb-430c-8efe-053a93ba2e95">

Any help would very appreciated!!

**Comment by brecht-horn** [comment]
HI @Marfuen sorry to reach out, but any chance you could help me with the above? How do I get the credits column to not be null?

**Comment by burgalon** [comment]
sounds like it's trying to update a null value in the database which shouldn't be the case. Please try to debug with the request payload and see what's being sent. The template is functional and deploying in many sites.
