### ISSUE TITLE
GitBounty: Switch to Astria's packs api

### ISSUE THREAD

**Issue by burgalon** [astriaai/headshots-starter#116]
Astria's packs API allows abstraction of the prompt logic and can easily allow offering separate themes and deploying changes with deploying code.

See docs: https://docs.astria.ai/docs/api/pack/pack/
The requested changes will apply the suggested user flow, with one change - to query both user's pack `/packs` as well as `/gallery/packs` (publicly available packs) according to an environment variable.

The GUI should implemented the workflow as described in the docs:

1. `GET /packs` Display a list of packs to the user. See [docs](https://docs.astria.ai/docs/api/pack/list/)
2. User selects a pack, a class name (man/woman) and training images
3. Call `POST /p/:id/tunes` with title, (training) images, and class name -  to create a new fine-tune model using a pack. See [docs](/docs/api/pack/tunes/create/)
4. `GET /tunes/:id/prompts` to get a list of prompts and their status
5. `POST /prompts/:id/likes` to send feedback to the API. See [docs](https://docs.astria.ai/docs/api/like/create/)
6. Sort prompts by likes
7. Present packs sorted by aggregated likes

https://gitpay.me/#/task/891

**Comment by ymohit1603** [comment]
Hey burgalon i want to work on this issue . Can you assign it to me?

**Comment by Precious-Macaulay** [comment]
Hey @burgalon i sent you a proposal on gitpay you can check it and assign it to me .
Also I will need some clarification on some part of the issue to ensure i truly understand what is required.

**Comment by Dheeraj4103** [comment]
Hey @burgalon Can I work on this issue ?

**Comment by burgalon** [comment]
hey @Dheeraj4103 please let's sync here on how to make sure this goes smoothly. Also available on chat on gmail

**Comment by Dheeraj4103** [comment]
Thanks @burgalon I will start working on this issue.

**Comment by burgalon** [comment]
I guess the offer is accepted once the PR is merged?

**Comment by burgalon** [comment]
@Dheeraj4103 can you please split the task into an initial first milestone which just includes using the packs api with a hard-coded pack id? i.e: only step 3. And then continue with the rest? Can you please share the timeline?

**Comment by Dheeraj4103** [comment]
Yeh sure @burgalon I will complete step 3 in this week.

**Comment by burgalon** [comment]
@Dheeraj4103 can you please update?

**Comment by Dheeraj4103** [comment]
Hey @burgalon can assign this task to someone else, because at the moment I have some other commitments.
Sorry for your inconvenience.

**Comment by Precious-Macaulay** [comment]
Hey @burgalon can you assign it to me so i can work on it immediately.

**Comment by burgalon** [comment]
@Precious-Macaulay are you available to start on this immediately? Can you please confirm that you understand the task, and the API docs? I'm available on Discord as `burgalon` for chat

**Comment by Precious-Macaulay** [comment]
Yes and i will follow up on discord.

**Comment by Precious-Macaulay** [comment]
So far I have implemented these requested changes in the latest commit. The user flow now queries both /packs (user's packs) and /gallery/packs (public packs) based on the environment variable. The GUI follows the described workflow: displaying the list of packs, allowing pack selection, class name, and images, and then submitting them via POST /p/:id/tunes to create a new fine-tune model.

**Comment by burgalon** [comment]
added `cover_url`, `base_prompts_count`, `prompt_likes_count`, `base_tunes_count`

**Comment by Precious-Macaulay** [comment]
> added `cover_url`, `base_prompts_count`, `prompt_likes_count`, `base_tunes_count`

alright i will work on that now.

**Comment by Precious-Macaulay** [comment]
@burgalon I was thinking if pack API is meant to replace the tune API in the app totally. so i can remove it instead of commenting it out just to keep the code clean.
Or maybe i can fine a way to make them work together in the app - so it will be more like the users choice. what do you think?
