### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by Durgesh4993** [astriaai/headshots-starter#68]
Sir can i add docker in Repository, which help to deploy applications quickly

**Comment by hjnnjh** [comment]
> Sir can i add docker in Repository, which help to deploy applications quickly

Me too, need a docker version.

**Comment by Marfuen** [comment]
@Durgesh4993 Feel free to add a dockerfile, and put up a PR

**Comment by Adidem23** [comment]
Please assign this issue to me @Durgesh4993

**Comment by Adidem23** [comment]
.take
