### ISSUE TITLE
Constantly training

### ISSUE THREAD

**Issue by markbrewster** [astriaai/headshots-starter#76]
I have an instance with Vercel/Supabase and when I add pictures and return to the overview I just get this:
![image](https://github.com/leap-ai/headshots-starter/assets/16579701/016d0a6d-6e40-47fb-93a9-bb802dbd240a)
It's been like this for 2 days! Haven't got it to work properly yet. I initially added 8 photos, then reduced it to the minimum of 4 to try again.

Any ideas? As I'm not sure where to even begin troubleshooting

**Comment by rossman22590** [comment]
where do you set up webhook i have same issue

**Comment by rossman22590** [comment]
only have this env: LEAP_WEBHOOK_SECRET

**Comment by rossman22590** [comment]
do i need any others?

**Comment by rossman22590** [comment]
any update?

**Comment by Marfuen** [comment]
Hey sorry for the delay, we've been pretty busy. In the latest version of the headshots template, the url in the /train-webhook file, is `const leapImageWebhookUrl = `https://${process.env.VERCEL_URL}/leap/image-webhook``. Also note that to test locally you have to use something like ngrok to test the webhook, and replace the process.env.VERCEL_URL with that url.

**Comment by rossman22590** [comment]
im using vercel, added VERCEL_URL  and still no, it finishes and trians for days

**Comment by kumardeepam** [comment]
> Hey sorry for the delay, we've been pretty busy. In the latest version of the headshots template, the url in the /train-webhook file, is `const leapImageWebhookUrl = `https://${process.env.VERCEL_URL}/leap/image-webhook``. Also note that to test locally you have to use something like ngrok to test the webhook, and replace the process.env.VERCEL_URL with that url.



> im using vercel, added VERCEL_URL and still no, it finishes and trians for days

Have you been able to make it work?

**Comment by kumardeepam** [comment]
> Hey sorry for the delay, we've been pretty busy. In the latest version of the headshots template, the url in the /train-webhook file, is `const leapImageWebhookUrl = `https://${process.env.VERCEL_URL}/leap/image-webhook``. Also note that to test locally you have to use something like ngrok to test the webhook, and replace the process.env.VERCEL_URL with that url.

Treid everything possible, still can't make it work :-| Please give it a look at https://picmaker.app/

**Comment by rossman22590** [comment]
same here man

**Comment by startupenko** [comment]
You have to pay for astria.ai. Only then will your training work well.

**Comment by chrisesmann** [comment]
Same problem here. Although the exact error in the Leap AI dashboard is: `Webhook call failed: {"cause":{"name":"RequestContentLengthMismatchError","code":"UND_ERR_REQ_CONTENT_LENGTH_MISMATCH","message":"Request body length does not match content-length header"}}`
